version: '3.8'

#
# REQUIREMENTS:
#   This docker-compose script depends on only one file on the host machine: ~/.kube/config
#   This is obtained by logging into https://portal.nrp-nautlius.io and being added to the
#   braingeneers namespace. Anyone who should have permissions to run this script should
#   have access to the namespace.
#

services:

  # The secret-fetcher container retrieves all secrets in the `braingeneers` namespace on kubernetes.
  # The files are saved to a shared volume typically mounted at `/secrets`. So for example, the AWS credentials
  # file would be found at `/secrets/prp-s3-credentials/credentials`.
  # The secret-fetcher container is typically a dependency of other containers that need access to the secrets.
  secret-fetcher:
    image: braingeneers/secret-fetcher:latest
    container_name: secret-fetcher
    user: root
    volumes:
      - ~/.kube/config:/.kube/config
      - secrets:/secrets
    environment:
      - KUBECONFIG=/.kube/config
    networks:
        - braingeneers-net

  # The nginx-proxy container is used to route traffic to the appropriate service based on the domain name.
  nginx-proxy:
    image: braingeneers/nginx-proxy:latest  # derived from jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    volumes:
      - /data/braingeneers-cache/certs:/etc/nginx/certs:rw  # Cache SSL certificates on the host
      - /data/braingeneers-cache/vhost:/etc/nginx/vhost.d
      - /data/braingeneers-cache/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro  # Unix socket mount to access docker API read-only
    networks:
      - braingeneers-net
    environment:
      - FORCE_INTERVAL=15s
      - LETSENCRYPT_HOST=braingeneers.gi.ucsc.edu
      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
      - LETSENCRYPT_TEST=false   # true | false for debugging | production (remember to set corresponding value in letsencrypt, it's used in run.sh in nginx container)
      - DEFAULT_HOST=braingeneers.gi.ucsc.edu
      - DEFAULT_PORT=80
    ports:
      - "80:80"
      - "443:443"

  # The letsencrypt container is used to automatically generate SSL certificates for the domain names.
  # https://github.com/jwilder/docker-letsencrypt-nginx-proxy-companion
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - LETSENCRYPT_TEST=false   # true | false for debugging | production (remember to set corresponding value in NGINX)
      - DEBUG=0   # 1 | 0 for debugging | production (remember to set corresponding value in nginx-proxy)
#      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory  # comment out for production use
    volumes:
      - /data/braingeneers-cache/certs:/etc/nginx/certs:rw  # Shared with nginx-proxy
      - /data/braingeneers-cache/vhost:/etc/nginx/vhost.d
      - /data/braingeneers-cache/html:/usr/share/nginx/html
      - /data/braingeneers-cache/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Unix socket mount to access docker API read-only
    depends_on:
      - nginx-proxy
    networks:
      - braingeneers-net

  # The oauth2_proxy container is used to authenticate users before they can access braingeneers services.
  oauth2-proxy:
    image: braingeneers/oauth2-proxy:latest
    container_name: oauth2-proxy
    command: /run.sh
    entrypoint: /bin/sh
    volumes:
      - /data/braingeneers-cache/certs:/etc/ssl/certs  # SSL certificates
      - secrets:/secrets
    networks:
      - braingeneers-net
    environment:
      # Settings to define a subdomain for this application
      - VIRTUAL_HOST=auth.braingeneers.gi.ucsc.edu
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=auth.braingeneers.gi.ucsc.edu
      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
    depends_on:
      - secret-fetcher

#  # The dashboard container is used to host the braingeneers dashboard.
#  dashboard:
#    image: braingeneers/dashboard:v1.5
#    container_name: dashboard
#    expose:
#      - "8050"
#    environment:
#      - VIRTUAL_HOST=dashboard.braingeneers.gi.ucsc.edu
#      - VIRTUAL_PORT=8050
#      - LETSENCRYPT_HOST=dashboard.braingeneers.gi.ucsc.edu
#      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
#    volumes:
#      - ~/.aws/credentials:/root/.aws/credentials:ro  # AWS credentials for your application
#    networks:
#      - braingeneers-net
#    depends_on:
#      - secret-fetcher

# Slack bridge service, replicates messages between Slack and MQTT
  slack-bridge:
    image: braingeneers/service-slack-bridge:latest
    container_name: slack-bridge
    networks:
      - braingeneers-net
    depends_on:
      - secret-fetcher
    volumes:
      - secrets:/secrets

# The braingeneers-net network is used to connect the containers together.
networks:
  braingeneers-net:
    driver: bridge

volumes:
  secrets:
    driver_opts:
      type: tmpfs
      device: tmpfs
