events {}
http {
    log_format vhost '$request_id $status';
    server {
        listen 8080;
        include /etc/nginx/vhost.d/uploader.braingeneers.gi.ucsc.edu;
        location / {
            include /etc/nginx/vhost.d/uploader.braingeneers.gi.ucsc.edu_location;
            proxy_pass http://127.0.0.1:8082;
        }
    }
    server {
        listen 8081;
        include /etc/nginx/vhost.d/uploader-dev.braingeneers.gi.ucsc.edu;
        location / {
            include /etc/nginx/vhost.d/uploader-dev.braingeneers.gi.ucsc.edu_location;
            proxy_pass http://127.0.0.1:8082;
        }
    }
    server {
        listen 4180;
        location /oauth2/auth {
            add_header X-Auth-Request-Email fixture@example.org always;
            if ($http_authorization = "Bearer test-auth") { return 204; }
            return 401;
        }
    }
    server {
        listen 8082;
        location / {
            add_header Observed-Email $http_x_email;
            add_header Observed-Authorization $http_authorization;
            add_header Observed-Length $http_content_length;
            return 200 'backend reached';
        }
    }
}
