apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: "2018-11-03T04:27:58Z"
  name: braingeneers-mem
  namespace: braingeneers
  resourceVersion: "7991743894"
  uid: d7c9320d-df20-11e8-ac6e-0cc47a6be994
spec:
  limits:
  - default:
      cpu: 1
      memory: 1Gi
    defaultRequest:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 1m
      memory: "256"
    type: Container
  - max:
      memory: 1Ti
    type: Pod
