apiVersion: v1
kind: Pod
metadata:
  name: lightning-pod
spec:
  containers:
  - name: podasaurusrex
    image: ubuntu:22.04
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 4Gi
        cpu: 2000m
      requests:
        memory: 4Gi
        cpu: 2000m
    volumeMounts:
    - mountPath: /workspace
      name: workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: whimvol
