apiVersion: batch/v1
kind: Job
metadata:
  name: job-h5repack-${UNIQUEID}
spec:
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 1000000000  # A very long time, approximately 31.7 years. (thanks GPT4)
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: h5repack
        image: braingeneers/job-h5repack:v${VERSION}
#        image: braingeneers/job-h5repack:latest
        imagePullPolicy: Always

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
          - >-
            /job_h5repack/h5repack_task.sh --random-delay 2

        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "4"
            memory: "12Gi"

        env:
          - name: "UUID"
            value: "${UUID}"
          - name: "AWS_PROFILE"
            value: "default"
          - name: "TF_CPP_MIN_LOG_LEVEL"
            value: "3"
          - name: "PYTHONUNBUFFERED"
            value: "true"

        volumeMounts:

          # Ceph & SWFS credentials
          - name: "prp-s3-credentials"
            mountPath: "/home/jovyan/.aws/credentials"
            subPath: "credentials"
          - name: "prp-s3-credentials"
            mountPath: "/home/jovyan/.s3cfg"
            subPath: ".s3cfg"

          # kube config
          - name: "kube-config"
            mountPath: "/home/jovyan/.kube"
          # SystemV shared memory
          - name: "dshm"
            mountPath: "/dev/shm"
          # Ephemeral storage
          - name: "ephemeral"
            mountPath: "/tmp"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              # Host blacklist
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - none

      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: kube-config
          secret:
            secretName: kube-config
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}